# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ewitis_qt_template_v0_1.ui'
#
# Created: Mon Jan 23 21:28:56 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1169, 582)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRuns_Times = QtGui.QWidget()
        self.tabRuns_Times.setObjectName(_fromUtf8("tabRuns_Times"))
        self.gridLayout = QtGui.QGridLayout(self.tabRuns_Times)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.RunsFilterLineEdit = QtGui.QLineEdit(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.RunsFilterLineEdit.setSizePolicy(sizePolicy)
        self.RunsFilterLineEdit.setDragEnabled(False)
        self.RunsFilterLineEdit.setObjectName(_fromUtf8("RunsFilterLineEdit"))
        self.gridLayout.addWidget(self.RunsFilterLineEdit, 0, 0, 1, 1)
        self.RunsFilterClear = QtGui.QPushButton(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsFilterClear.sizePolicy().hasHeightForWidth())
        self.RunsFilterClear.setSizePolicy(sizePolicy)
        self.RunsFilterClear.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/mail-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsFilterClear.setIcon(icon)
        self.RunsFilterClear.setFlat(True)
        self.RunsFilterClear.setObjectName(_fromUtf8("RunsFilterClear"))
        self.gridLayout.addWidget(self.RunsFilterClear, 0, 1, 1, 1)
        self.RunsProxyView = QtGui.QTreeView(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsProxyView.sizePolicy().hasHeightForWidth())
        self.RunsProxyView.setSizePolicy(sizePolicy)
        self.RunsProxyView.setObjectName(_fromUtf8("RunsProxyView"))
        self.gridLayout.addWidget(self.RunsProxyView, 1, 0, 1, 4)
        self.runsCounter = QtGui.QLabel(self.tabRuns_Times)
        self.runsCounter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runsCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.runsCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runsCounter.setObjectName(_fromUtf8("runsCounter"))
        self.gridLayout.addWidget(self.runsCounter, 2, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabRuns_Times)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.RunsAdd = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsAdd.sizePolicy().hasHeightForWidth())
        self.RunsAdd.setSizePolicy(sizePolicy)
        self.RunsAdd.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsAdd.setIcon(icon1)
        self.RunsAdd.setIconSize(QtCore.QSize(24, 24))
        self.RunsAdd.setAutoDefault(False)
        self.RunsAdd.setDefault(False)
        self.RunsAdd.setObjectName(_fromUtf8("RunsAdd"))
        self.horizontalLayout_2.addWidget(self.RunsAdd)
        self.RunsRemove = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsRemove.sizePolicy().hasHeightForWidth())
        self.RunsRemove.setSizePolicy(sizePolicy)
        self.RunsRemove.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsRemove.setIcon(icon2)
        self.RunsRemove.setIconSize(QtCore.QSize(24, 24))
        self.RunsRemove.setObjectName(_fromUtf8("RunsRemove"))
        self.horizontalLayout_2.addWidget(self.RunsRemove)
        self.RunsExport = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsExport.sizePolicy().hasHeightForWidth())
        self.RunsExport.setSizePolicy(sizePolicy)
        self.RunsExport.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsExport.setIcon(icon3)
        self.RunsExport.setIconSize(QtCore.QSize(24, 24))
        self.RunsExport.setObjectName(_fromUtf8("RunsExport"))
        self.horizontalLayout_2.addWidget(self.RunsExport)
        self.RunsDelete = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsDelete.sizePolicy().hasHeightForWidth())
        self.RunsDelete.setSizePolicy(sizePolicy)
        self.RunsDelete.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/emptytrash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsDelete.setIcon(icon4)
        self.RunsDelete.setIconSize(QtCore.QSize(24, 24))
        self.RunsDelete.setObjectName(_fromUtf8("RunsDelete"))
        self.horizontalLayout_2.addWidget(self.RunsDelete)
        self.gridLayout.addWidget(self.groupBox_2, 0, 3, 1, 1)
        self.TimesShowAll = QtGui.QCheckBox(self.tabRuns_Times)
        self.TimesShowAll.setText(QtGui.QApplication.translate("MainWindow", "All Times", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesShowAll.setObjectName(_fromUtf8("TimesShowAll"))
        self.gridLayout.addWidget(self.TimesShowAll, 0, 8, 1, 1)
        self.TimesFilterLineEdit = QtGui.QLineEdit(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.TimesFilterLineEdit.setSizePolicy(sizePolicy)
        self.TimesFilterLineEdit.setObjectName(_fromUtf8("TimesFilterLineEdit"))
        self.gridLayout.addWidget(self.TimesFilterLineEdit, 0, 5, 1, 1)
        self.TimesFilterClear = QtGui.QPushButton(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesFilterClear.sizePolicy().hasHeightForWidth())
        self.TimesFilterClear.setSizePolicy(sizePolicy)
        self.TimesFilterClear.setText(_fromUtf8(""))
        self.TimesFilterClear.setIcon(icon)
        self.TimesFilterClear.setFlat(True)
        self.TimesFilterClear.setObjectName(_fromUtf8("TimesFilterClear"))
        self.gridLayout.addWidget(self.TimesFilterClear, 0, 6, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tabRuns_Times)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.TimesAdd = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesAdd.sizePolicy().hasHeightForWidth())
        self.TimesAdd.setSizePolicy(sizePolicy)
        self.TimesAdd.setText(_fromUtf8(""))
        self.TimesAdd.setIcon(icon1)
        self.TimesAdd.setIconSize(QtCore.QSize(24, 24))
        self.TimesAdd.setAutoDefault(False)
        self.TimesAdd.setDefault(False)
        self.TimesAdd.setObjectName(_fromUtf8("TimesAdd"))
        self.horizontalLayout_3.addWidget(self.TimesAdd)
        self.TimesRemove = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesRemove.sizePolicy().hasHeightForWidth())
        self.TimesRemove.setSizePolicy(sizePolicy)
        self.TimesRemove.setText(_fromUtf8(""))
        self.TimesRemove.setIcon(icon2)
        self.TimesRemove.setIconSize(QtCore.QSize(24, 24))
        self.TimesRemove.setObjectName(_fromUtf8("TimesRemove"))
        self.horizontalLayout_3.addWidget(self.TimesRemove)
        self.TimesImport = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesImport.sizePolicy().hasHeightForWidth())
        self.TimesImport.setSizePolicy(sizePolicy)
        self.TimesImport.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesImport.setIcon(icon5)
        self.TimesImport.setIconSize(QtCore.QSize(24, 24))
        self.TimesImport.setObjectName(_fromUtf8("TimesImport"))
        self.horizontalLayout_3.addWidget(self.TimesImport)
        self.TimesExport = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesExport.sizePolicy().hasHeightForWidth())
        self.TimesExport.setSizePolicy(sizePolicy)
        self.TimesExport.setText(_fromUtf8(""))
        self.TimesExport.setIcon(icon3)
        self.TimesExport.setIconSize(QtCore.QSize(24, 24))
        self.TimesExport.setObjectName(_fromUtf8("TimesExport"))
        self.horizontalLayout_3.addWidget(self.TimesExport)
        self.TimesWwwExport = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesWwwExport.sizePolicy().hasHeightForWidth())
        self.TimesWwwExport.setSizePolicy(sizePolicy)
        self.TimesWwwExport.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/internet-web-browser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesWwwExport.setIcon(icon6)
        self.TimesWwwExport.setIconSize(QtCore.QSize(24, 24))
        self.TimesWwwExport.setObjectName(_fromUtf8("TimesWwwExport"))
        self.horizontalLayout_3.addWidget(self.TimesWwwExport)
        self.TimesDelete = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesDelete.sizePolicy().hasHeightForWidth())
        self.TimesDelete.setSizePolicy(sizePolicy)
        self.TimesDelete.setText(_fromUtf8(""))
        self.TimesDelete.setIcon(icon4)
        self.TimesDelete.setIconSize(QtCore.QSize(24, 24))
        self.TimesDelete.setObjectName(_fromUtf8("TimesDelete"))
        self.horizontalLayout_3.addWidget(self.TimesDelete)
        self.gridLayout.addWidget(self.groupBox_3, 0, 9, 1, 1)
        self.TimesProxyView = QtGui.QTreeView(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesProxyView.sizePolicy().hasHeightForWidth())
        self.TimesProxyView.setSizePolicy(sizePolicy)
        self.TimesProxyView.setObjectName(_fromUtf8("TimesProxyView"))
        self.gridLayout.addWidget(self.TimesProxyView, 1, 5, 1, 5)
        self.timesShowZero = QtGui.QCheckBox(self.tabRuns_Times)
        self.timesShowZero.setText(QtGui.QApplication.translate("MainWindow", "Zero Times", None, QtGui.QApplication.UnicodeUTF8))
        self.timesShowZero.setObjectName(_fromUtf8("timesShowZero"))
        self.gridLayout.addWidget(self.timesShowZero, 0, 7, 1, 1)
        self.timesCounter = QtGui.QLabel(self.tabRuns_Times)
        self.timesCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.timesCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timesCounter.setObjectName(_fromUtf8("timesCounter"))
        self.gridLayout.addWidget(self.timesCounter, 2, 9, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tabRuns_Times, _fromUtf8(""))
        self.tabUsers = QtGui.QWidget()
        self.tabUsers.setObjectName(_fromUtf8("tabUsers"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabUsers)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.UsersFilterLineEdit = QtGui.QLineEdit(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.UsersFilterLineEdit.setSizePolicy(sizePolicy)
        self.UsersFilterLineEdit.setObjectName(_fromUtf8("UsersFilterLineEdit"))
        self.gridLayout_2.addWidget(self.UsersFilterLineEdit, 0, 0, 1, 1)
        self.usersCounter = QtGui.QLabel(self.tabUsers)
        self.usersCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.usersCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usersCounter.setObjectName(_fromUtf8("usersCounter"))
        self.gridLayout_2.addWidget(self.usersCounter, 2, 5, 1, 1)
        self.UsersProxyView = QtGui.QTreeView(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersProxyView.sizePolicy().hasHeightForWidth())
        self.UsersProxyView.setSizePolicy(sizePolicy)
        self.UsersProxyView.setObjectName(_fromUtf8("UsersProxyView"))
        self.gridLayout_2.addWidget(self.UsersProxyView, 1, 0, 1, 6)
        self.UsersFilterClear = QtGui.QPushButton(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersFilterClear.sizePolicy().hasHeightForWidth())
        self.UsersFilterClear.setSizePolicy(sizePolicy)
        self.UsersFilterClear.setText(_fromUtf8(""))
        self.UsersFilterClear.setIcon(icon)
        self.UsersFilterClear.setFlat(True)
        self.UsersFilterClear.setObjectName(_fromUtf8("UsersFilterClear"))
        self.gridLayout_2.addWidget(self.UsersFilterClear, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.UsersAdd = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersAdd.sizePolicy().hasHeightForWidth())
        self.UsersAdd.setSizePolicy(sizePolicy)
        self.UsersAdd.setText(_fromUtf8(""))
        self.UsersAdd.setIcon(icon1)
        self.UsersAdd.setIconSize(QtCore.QSize(24, 24))
        self.UsersAdd.setAutoDefault(False)
        self.UsersAdd.setDefault(False)
        self.UsersAdd.setObjectName(_fromUtf8("UsersAdd"))
        self.horizontalLayout_8.addWidget(self.UsersAdd)
        self.UsersRemove = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersRemove.sizePolicy().hasHeightForWidth())
        self.UsersRemove.setSizePolicy(sizePolicy)
        self.UsersRemove.setText(_fromUtf8(""))
        self.UsersRemove.setIcon(icon2)
        self.UsersRemove.setIconSize(QtCore.QSize(24, 24))
        self.UsersRemove.setObjectName(_fromUtf8("UsersRemove"))
        self.horizontalLayout_8.addWidget(self.UsersRemove)
        self.UsersImport = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersImport.sizePolicy().hasHeightForWidth())
        self.UsersImport.setSizePolicy(sizePolicy)
        self.UsersImport.setText(_fromUtf8(""))
        self.UsersImport.setIcon(icon5)
        self.UsersImport.setIconSize(QtCore.QSize(24, 24))
        self.UsersImport.setObjectName(_fromUtf8("UsersImport"))
        self.horizontalLayout_8.addWidget(self.UsersImport)
        self.UsersExport = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersExport.sizePolicy().hasHeightForWidth())
        self.UsersExport.setSizePolicy(sizePolicy)
        self.UsersExport.setText(_fromUtf8(""))
        self.UsersExport.setIcon(icon3)
        self.UsersExport.setIconSize(QtCore.QSize(24, 24))
        self.UsersExport.setObjectName(_fromUtf8("UsersExport"))
        self.horizontalLayout_8.addWidget(self.UsersExport)
        self.UsersDelete = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersDelete.sizePolicy().hasHeightForWidth())
        self.UsersDelete.setSizePolicy(sizePolicy)
        self.UsersDelete.setText(_fromUtf8(""))
        self.UsersDelete.setIcon(icon4)
        self.UsersDelete.setIconSize(QtCore.QSize(24, 24))
        self.UsersDelete.setObjectName(_fromUtf8("UsersDelete"))
        self.horizontalLayout_8.addWidget(self.UsersDelete)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 5, 1, 1)
        self.tabWidget.addTab(self.tabUsers, _fromUtf8(""))
        self.tabCategories = QtGui.QWidget()
        self.tabCategories.setObjectName(_fromUtf8("tabCategories"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCategories)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.CategoriesFilterLineEdit = QtGui.QLineEdit(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.CategoriesFilterLineEdit.setSizePolicy(sizePolicy)
        self.CategoriesFilterLineEdit.setObjectName(_fromUtf8("CategoriesFilterLineEdit"))
        self.gridLayout_3.addWidget(self.CategoriesFilterLineEdit, 0, 0, 1, 1)
        self.CategoriesFilterClear = QtGui.QPushButton(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesFilterClear.sizePolicy().hasHeightForWidth())
        self.CategoriesFilterClear.setSizePolicy(sizePolicy)
        self.CategoriesFilterClear.setText(_fromUtf8(""))
        self.CategoriesFilterClear.setIcon(icon)
        self.CategoriesFilterClear.setAutoRepeat(False)
        self.CategoriesFilterClear.setFlat(True)
        self.CategoriesFilterClear.setObjectName(_fromUtf8("CategoriesFilterClear"))
        self.gridLayout_3.addWidget(self.CategoriesFilterClear, 0, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.CategoriesAdd = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesAdd.sizePolicy().hasHeightForWidth())
        self.CategoriesAdd.setSizePolicy(sizePolicy)
        self.CategoriesAdd.setText(_fromUtf8(""))
        self.CategoriesAdd.setIcon(icon1)
        self.CategoriesAdd.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesAdd.setAutoDefault(False)
        self.CategoriesAdd.setDefault(False)
        self.CategoriesAdd.setObjectName(_fromUtf8("CategoriesAdd"))
        self.horizontalLayout_9.addWidget(self.CategoriesAdd)
        self.CategoriesRemove = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesRemove.sizePolicy().hasHeightForWidth())
        self.CategoriesRemove.setSizePolicy(sizePolicy)
        self.CategoriesRemove.setText(_fromUtf8(""))
        self.CategoriesRemove.setIcon(icon2)
        self.CategoriesRemove.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesRemove.setObjectName(_fromUtf8("CategoriesRemove"))
        self.horizontalLayout_9.addWidget(self.CategoriesRemove)
        self.CategoriesImport = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesImport.sizePolicy().hasHeightForWidth())
        self.CategoriesImport.setSizePolicy(sizePolicy)
        self.CategoriesImport.setText(_fromUtf8(""))
        self.CategoriesImport.setIcon(icon5)
        self.CategoriesImport.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesImport.setObjectName(_fromUtf8("CategoriesImport"))
        self.horizontalLayout_9.addWidget(self.CategoriesImport)
        self.CategoriesExport = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesExport.sizePolicy().hasHeightForWidth())
        self.CategoriesExport.setSizePolicy(sizePolicy)
        self.CategoriesExport.setText(_fromUtf8(""))
        self.CategoriesExport.setIcon(icon3)
        self.CategoriesExport.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesExport.setObjectName(_fromUtf8("CategoriesExport"))
        self.horizontalLayout_9.addWidget(self.CategoriesExport)
        self.CategoriesDelete = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesDelete.sizePolicy().hasHeightForWidth())
        self.CategoriesDelete.setSizePolicy(sizePolicy)
        self.CategoriesDelete.setText(_fromUtf8(""))
        self.CategoriesDelete.setIcon(icon4)
        self.CategoriesDelete.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesDelete.setObjectName(_fromUtf8("CategoriesDelete"))
        self.horizontalLayout_9.addWidget(self.CategoriesDelete)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 3, 1, 1)
        self.CategoriesProxyView = QtGui.QTreeView(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesProxyView.sizePolicy().hasHeightForWidth())
        self.CategoriesProxyView.setSizePolicy(sizePolicy)
        self.CategoriesProxyView.setObjectName(_fromUtf8("CategoriesProxyView"))
        self.gridLayout_3.addWidget(self.CategoriesProxyView, 1, 0, 1, 4)
        self.CategoriesCounter = QtGui.QLabel(self.tabCategories)
        self.CategoriesCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.CategoriesCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CategoriesCounter.setObjectName(_fromUtf8("CategoriesCounter"))
        self.gridLayout_3.addWidget(self.CategoriesCounter, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabCategories, _fromUtf8(""))
        self.tabTerminal = QtGui.QWidget()
        self.tabTerminal.setObjectName(_fromUtf8("tabTerminal"))
        self.tabWidget.addTab(self.tabTerminal, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolbar = QtGui.QToolBar(MainWindow)
        self.toolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.toolbarPort = QtGui.QToolBar(MainWindow)
        self.toolbarPort.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarPort.setObjectName(_fromUtf8("toolbarPort"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbarPort)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.aRefresh = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aRefresh.setIcon(icon7)
        self.aRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefresh.setObjectName(_fromUtf8("aRefresh"))
        self.aSetPort = QtGui.QAction(MainWindow)
        self.aSetPort.setText(QtGui.QApplication.translate("MainWindow", "COM21", None, QtGui.QApplication.UnicodeUTF8))
        self.aSetPort.setObjectName(_fromUtf8("aSetPort"))
        self.aConnectPort = QtGui.QAction(MainWindow)
        self.aConnectPort.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setObjectName(_fromUtf8("aConnectPort"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.aEditMode = QtGui.QAction(MainWindow)
        self.aEditMode.setText(QtGui.QApplication.translate("MainWindow", "EditMode", None, QtGui.QApplication.UnicodeUTF8))
        self.aEditMode.setObjectName(_fromUtf8("aEditMode"))
        self.aRefreshMode = QtGui.QAction(MainWindow)
        self.aRefreshMode.setText(QtGui.QApplication.translate("MainWindow", "RefreshMode", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefreshMode.setObjectName(_fromUtf8("aRefreshMode"))
        self.aLockMode = QtGui.QAction(MainWindow)
        self.aLockMode.setText(QtGui.QApplication.translate("MainWindow", "LockMode", None, QtGui.QApplication.UnicodeUTF8))
        self.aLockMode.setObjectName(_fromUtf8("aLockMode"))
        self.aDirectWwwExport = QtGui.QAction(MainWindow)
        self.aDirectWwwExport.setText(QtGui.QApplication.translate("MainWindow", "Direct WWW Export", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectWwwExport.setObjectName(_fromUtf8("aDirectWwwExport"))
        self.aDirectExportCategories = QtGui.QAction(MainWindow)
        self.aDirectExportCategories.setText(QtGui.QApplication.translate("MainWindow", "Direct Export Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectExportCategories.setObjectName(_fromUtf8("aDirectExportCategories"))
        self.aShortcuts = QtGui.QAction(MainWindow)
        self.aShortcuts.setText(QtGui.QApplication.translate("MainWindow", "Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.aShortcuts.setObjectName(_fromUtf8("aShortcuts"))
        self.menuDatabase.addAction(self.actionLoad)
        self.menuDatabase.addAction(self.actionSave)
        self.menuDatabase.addAction(self.actionSave_as)
        self.menuActions.addAction(self.aRefresh)
        self.menuActions.addAction(self.aSetPort)
        self.menuActions.addAction(self.aConnectPort)
        self.menuActions.addAction(self.actionAbout)
        self.menuActions.addAction(self.actionHelp)
        self.menuActions.addAction(self.aEditMode)
        self.menuActions.addAction(self.aRefreshMode)
        self.menuActions.addAction(self.aLockMode)
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolbar.addAction(self.aRefresh)
        self.toolbarPort.addAction(self.aSetPort)
        self.toolbarPort.addAction(self.aConnectPort)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRuns_Times), QtGui.QApplication.translate("MainWindow", "Runs#Times", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUsers), QtGui.QApplication.translate("MainWindow", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCategories), QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTerminal), QtGui.QApplication.translate("MainWindow", "Terminal", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

