# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ewitis_grid.ui'
#
# Created: Mon May 23 15:10:46 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 504)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setToolTip("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabRuns_Times = QtGui.QWidget()
        self.tabRuns_Times.setObjectName("tabRuns_Times")
        self.gridLayout = QtGui.QGridLayout(self.tabRuns_Times)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.RunsFilterClear = QtGui.QPushButton(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsFilterClear.sizePolicy().hasHeightForWidth())
        self.RunsFilterClear.setSizePolicy(sizePolicy)
        self.RunsFilterClear.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icons/mail-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsFilterClear.setIcon(icon)
        self.RunsFilterClear.setIconSize(QtCore.QSize(16, 16))
        self.RunsFilterClear.setFlat(True)
        self.RunsFilterClear.setObjectName("RunsFilterClear")
        self.gridLayout.addWidget(self.RunsFilterClear, 1, 1, 1, 1)
        self.TimesFilterLineEdit = QtGui.QLineEdit(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.TimesFilterLineEdit.setSizePolicy(sizePolicy)
        self.TimesFilterLineEdit.setObjectName("TimesFilterLineEdit")
        self.gridLayout.addWidget(self.TimesFilterLineEdit, 1, 6, 1, 1)
        self.TimesFilterClear = QtGui.QPushButton(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesFilterClear.sizePolicy().hasHeightForWidth())
        self.TimesFilterClear.setSizePolicy(sizePolicy)
        self.TimesFilterClear.setText("")
        self.TimesFilterClear.setIcon(icon)
        self.TimesFilterClear.setIconSize(QtCore.QSize(16, 16))
        self.TimesFilterClear.setFlat(True)
        self.TimesFilterClear.setObjectName("TimesFilterClear")
        self.gridLayout.addWidget(self.TimesFilterClear, 1, 7, 1, 1)
        self.RunsProxyView = QtGui.QTreeView(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsProxyView.sizePolicy().hasHeightForWidth())
        self.RunsProxyView.setSizePolicy(sizePolicy)
        self.RunsProxyView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.RunsProxyView.setObjectName("RunsProxyView")
        self.gridLayout.addWidget(self.RunsProxyView, 3, 0, 1, 5)
        self.TimesProxyView = QtGui.QTreeView(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesProxyView.sizePolicy().hasHeightForWidth())
        self.TimesProxyView.setSizePolicy(sizePolicy)
        self.TimesProxyView.setObjectName("TimesProxyView")
        self.gridLayout.addWidget(self.TimesProxyView, 3, 6, 1, 7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 8, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 2)
        self.TimesIcons = QtGui.QGroupBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesIcons.sizePolicy().hasHeightForWidth())
        self.TimesIcons.setSizePolicy(sizePolicy)
        self.TimesIcons.setTitle("")
        self.TimesIcons.setObjectName("TimesIcons")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.TimesIcons)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TimesAdd = QtGui.QPushButton(self.TimesIcons)
        self.TimesAdd.setEnabled(True)
        self.TimesAdd.setCursor(QtCore.Qt.PointingHandCursor)
        self.TimesAdd.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesAdd.setIcon(icon1)
        self.TimesAdd.setIconSize(QtCore.QSize(24, 24))
        self.TimesAdd.setAutoDefault(True)
        self.TimesAdd.setDefault(True)
        self.TimesAdd.setFlat(False)
        self.TimesAdd.setObjectName("TimesAdd")
        self.horizontalLayout_4.addWidget(self.TimesAdd)
        self.TimesRemove = QtGui.QPushButton(self.TimesIcons)
        self.TimesRemove.setCursor(QtCore.Qt.PointingHandCursor)
        self.TimesRemove.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/icons/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesRemove.setIcon(icon2)
        self.TimesRemove.setIconSize(QtCore.QSize(24, 24))
        self.TimesRemove.setAutoDefault(True)
        self.TimesRemove.setDefault(True)
        self.TimesRemove.setFlat(False)
        self.TimesRemove.setObjectName("TimesRemove")
        self.horizontalLayout_4.addWidget(self.TimesRemove)
        self.TimesExport = QtGui.QPushButton(self.TimesIcons)
        self.TimesExport.setCursor(QtCore.Qt.PointingHandCursor)
        self.TimesExport.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesExport.setIcon(icon3)
        self.TimesExport.setIconSize(QtCore.QSize(24, 24))
        self.TimesExport.setAutoDefault(True)
        self.TimesExport.setDefault(True)
        self.TimesExport.setFlat(False)
        self.TimesExport.setObjectName("TimesExport")
        self.horizontalLayout_4.addWidget(self.TimesExport)
        
       
        self.TimesWwwExport = QtGui.QPushButton(self.TimesIcons)
        self.TimesWwwExport.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/icons/internet-web-browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesWwwExport.setIcon(icon4)
        self.TimesWwwExport.setIconSize(QtCore.QSize(24, 24))
        self.TimesWwwExport.setAutoDefault(True)
        self.TimesWwwExport.setDefault(True)
        self.TimesWwwExport.setObjectName("TimesWwwExport")
        self.horizontalLayout_4.addWidget(self.TimesWwwExport)
        self.TimesDelete = QtGui.QPushButton(self.TimesIcons)
        self.TimesDelete.setCursor(QtCore.Qt.PointingHandCursor)
        self.TimesDelete.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui/icons/emptytrash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesDelete.setIcon(icon5)
        self.TimesDelete.setIconSize(QtCore.QSize(24, 24))
        self.TimesDelete.setAutoDefault(True)
        self.TimesDelete.setDefault(True)
        self.TimesDelete.setFlat(False)
        self.TimesDelete.setObjectName("TimesDelete")
        self.horizontalLayout_4.addWidget(self.TimesDelete)
        self.gridLayout.addWidget(self.TimesIcons, 1, 12, 1, 1)
        self.RunsFilterLineEdit = QtGui.QLineEdit(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.RunsFilterLineEdit.setSizePolicy(sizePolicy)
        self.RunsFilterLineEdit.setObjectName("RunsFilterLineEdit")
        self.gridLayout.addWidget(self.RunsFilterLineEdit, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        self.TimesShowAll = QtGui.QCheckBox(self.tabRuns_Times)
        self.TimesShowAll.setObjectName("TimesShowAll")
        self.gridLayout.addWidget(self.TimesShowAll, 1, 11, 1, 1)
        self.timesCounter = QtGui.QLabel(self.tabRuns_Times)
        self.timesCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timesCounter.setObjectName("timesCounter")
        self.gridLayout.addWidget(self.timesCounter, 4, 12, 1, 1)
        self.timesShowZero = QtGui.QCheckBox(self.tabRuns_Times)
        self.timesShowZero.setChecked(True)
        self.timesShowZero.setObjectName("timesShowZero")
        self.gridLayout.addWidget(self.timesShowZero, 1, 10, 1, 1)
        self.RunsIcons = QtGui.QGroupBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsIcons.sizePolicy().hasHeightForWidth())
        self.RunsIcons.setSizePolicy(sizePolicy)
        self.RunsIcons.setTitle("")
        self.RunsIcons.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RunsIcons.setObjectName("RunsIcons")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.RunsIcons)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RunsAdd = QtGui.QPushButton(self.RunsIcons)
        self.RunsAdd.setCursor(QtCore.Qt.PointingHandCursor)
        self.RunsAdd.setText("")
        self.RunsAdd.setIcon(icon1)
        self.RunsAdd.setIconSize(QtCore.QSize(24, 24))
        self.RunsAdd.setAutoDefault(True)
        self.RunsAdd.setDefault(True)
        self.RunsAdd.setFlat(False)
        self.RunsAdd.setObjectName("RunsAdd")
        self.horizontalLayout_3.addWidget(self.RunsAdd)
        self.RunsRemove = QtGui.QPushButton(self.RunsIcons)
        self.RunsRemove.setCursor(QtCore.Qt.PointingHandCursor)
        self.RunsRemove.setText("")
        self.RunsRemove.setIcon(icon2)
        self.RunsRemove.setIconSize(QtCore.QSize(24, 24))
        self.RunsRemove.setAutoDefault(True)
        self.RunsRemove.setDefault(True)
        self.RunsRemove.setFlat(False)
        self.RunsRemove.setObjectName("RunsRemove")
        self.horizontalLayout_3.addWidget(self.RunsRemove)
        self.RunsExport = QtGui.QPushButton(self.RunsIcons)
        self.RunsExport.setCursor(QtCore.Qt.PointingHandCursor)
        self.RunsExport.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.RunsExport.setText("")
        self.RunsExport.setIcon(icon3)
        self.RunsExport.setIconSize(QtCore.QSize(24, 24))
        self.RunsExport.setAutoDefault(True)
        self.RunsExport.setDefault(True)
        self.RunsExport.setFlat(False)
        self.RunsExport.setObjectName("RunsExport")
        self.horizontalLayout_3.addWidget(self.RunsExport)
        self.RunsDelete = QtGui.QPushButton(self.RunsIcons)
        self.RunsDelete.setCursor(QtCore.Qt.PointingHandCursor)
        self.RunsDelete.setText("")
        self.RunsDelete.setIcon(icon5)
        self.RunsDelete.setIconSize(QtCore.QSize(24, 24))
        self.RunsDelete.setAutoDefault(True)
        self.RunsDelete.setDefault(True)
        self.RunsDelete.setFlat(False)
        self.RunsDelete.setObjectName("RunsDelete")
        self.horizontalLayout_3.addWidget(self.RunsDelete)
        self.gridLayout.addWidget(self.RunsIcons, 1, 4, 1, 1)
        self.runsCounter = QtGui.QLabel(self.tabRuns_Times)
        self.runsCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runsCounter.setObjectName("runsCounter")
        self.gridLayout.addWidget(self.runsCounter, 4, 4, 1, 1)
        self.tabWidget.addTab(self.tabRuns_Times, "")
        self.tabUsers = QtGui.QWidget()
        self.tabUsers.setObjectName("tabUsers")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabUsers)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.UsersFilterLineEdit = QtGui.QLineEdit(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.UsersFilterLineEdit.setSizePolicy(sizePolicy)
        self.UsersFilterLineEdit.setObjectName("UsersFilterLineEdit")
        self.gridLayout_2.addWidget(self.UsersFilterLineEdit, 0, 0, 1, 1)
        self.UsersFilterClear = QtGui.QPushButton(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersFilterClear.sizePolicy().hasHeightForWidth())
        self.UsersFilterClear.setSizePolicy(sizePolicy)
        self.UsersFilterClear.setText("")
        self.UsersFilterClear.setIcon(icon)
        self.UsersFilterClear.setIconSize(QtCore.QSize(16, 16))
        self.UsersFilterClear.setFlat(True)
        self.UsersFilterClear.setObjectName("UsersFilterClear")
        self.gridLayout_2.addWidget(self.UsersFilterClear, 0, 1, 1, 1)
        self.UsersIcons = QtGui.QGroupBox(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersIcons.sizePolicy().hasHeightForWidth())
        self.UsersIcons.setSizePolicy(sizePolicy)
        self.UsersIcons.setTitle("")
        self.UsersIcons.setObjectName("UsersIcons")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.UsersIcons)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UsersAdd = QtGui.QPushButton(self.UsersIcons)
        self.UsersAdd.setText("")
        self.UsersAdd.setIcon(icon1)
        self.UsersAdd.setIconSize(QtCore.QSize(24, 24))
        self.UsersAdd.setAutoDefault(True)
        self.UsersAdd.setDefault(True)
        self.UsersAdd.setFlat(False)
        self.UsersAdd.setObjectName("UsersAdd")
        self.horizontalLayout_2.addWidget(self.UsersAdd)
        self.UsersRemove = QtGui.QPushButton(self.UsersIcons)
        self.UsersRemove.setText("")
        self.UsersRemove.setIcon(icon2)
        self.UsersRemove.setIconSize(QtCore.QSize(24, 24))
        self.UsersRemove.setAutoDefault(True)
        self.UsersRemove.setDefault(True)
        self.UsersRemove.setFlat(False)
        self.UsersRemove.setObjectName("UsersRemove")
        self.horizontalLayout_2.addWidget(self.UsersRemove)
        self.UsersExport = QtGui.QPushButton(self.UsersIcons)
        self.UsersExport.setText("")
        self.UsersExport.setIcon(icon3)
        self.UsersExport.setIconSize(QtCore.QSize(24, 24))
        self.UsersExport.setAutoDefault(True)
        self.UsersExport.setDefault(True)
        self.UsersExport.setFlat(False)
        self.UsersExport.setObjectName("UsersExport")
        self.horizontalLayout_2.addWidget(self.UsersExport)
        self.UsersImport = QtGui.QPushButton(self.UsersIcons)
        self.UsersImport.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("gui/icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UsersImport.setIcon(icon6)
        self.UsersImport.setIconSize(QtCore.QSize(24, 24))
        self.UsersImport.setAutoDefault(True)
        self.UsersImport.setDefault(True)
        self.UsersImport.setFlat(False)
        self.UsersImport.setObjectName("UsersImport")
        self.horizontalLayout_2.addWidget(self.UsersImport)
        self.UsersDelete = QtGui.QPushButton(self.UsersIcons)
        self.UsersDelete.setText("")
        self.UsersDelete.setIcon(icon5)
        self.UsersDelete.setIconSize(QtCore.QSize(24, 24))
        self.UsersDelete.setAutoDefault(True)
        self.UsersDelete.setDefault(True)
        self.UsersDelete.setFlat(False)
        self.UsersDelete.setObjectName("UsersDelete")
        self.horizontalLayout_2.addWidget(self.UsersDelete)
        self.gridLayout_2.addWidget(self.UsersIcons, 0, 3, 1, 1)
        self.UsersProxyView = QtGui.QTreeView(self.tabUsers)
        self.UsersProxyView.setObjectName("UsersProxyView")
        self.gridLayout_2.addWidget(self.UsersProxyView, 1, 0, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.usersCounter = QtGui.QLabel(self.tabUsers)
        self.usersCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usersCounter.setObjectName("usersCounter")
        self.gridLayout_2.addWidget(self.usersCounter, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabUsers, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 20))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName("menubar")
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setEnabled(True)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuMode = QtGui.QMenu(self.menuSettings)
        self.menuMode.setObjectName("menuMode")
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_Port = QtGui.QToolBar(MainWindow)
        self.toolBar_Port.setEnabled(True)
        self.toolBar_Port.setObjectName("toolBar_Port")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Port)
        self.toolBar_Action = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar_Action.sizePolicy().hasHeightForWidth())
        self.toolBar_Action.setSizePolicy(sizePolicy)
        self.toolBar_Action.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar_Action.setObjectName("toolBar_Action")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Action)
        self.toolBar_Modes = QtGui.QToolBar(MainWindow)
        self.toolBar_Modes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_Modes.setObjectName("toolBar_Modes")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Modes)
        self.aSetPort = QtGui.QAction(MainWindow)
        self.aSetPort.setEnabled(True)
        self.aSetPort.setObjectName("aSetPort")
        self.aConnectPort = QtGui.QAction(MainWindow)
        self.aConnectPort.setObjectName("aConnectPort")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setEnabled(False)
        self.actionHelp.setObjectName("actionHelp")
        self.aRefresh = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("gui/icons/view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aRefresh.setIcon(icon7)
        self.aRefresh.setObjectName("aRefresh")
        self.aEditMode = QtGui.QAction(MainWindow)
        self.aEditMode.setCheckable(True)
        self.aEditMode.setChecked(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("gui/icons/pencil2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aEditMode.setIcon(icon8)
        self.aEditMode.setObjectName("aEditMode")
        self.aRefreshMode = QtGui.QAction(MainWindow)
        self.aRefreshMode.setCheckable(True)
        self.aRefreshMode.setChecked(False)
        self.aRefreshMode.setIcon(icon7)
        self.aRefreshMode.setIconVisibleInMenu(True)
        self.aRefreshMode.setObjectName("aRefreshMode")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setCheckable(False)
        self.actionLoad.setChecked(False)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.aLockMode = QtGui.QAction(MainWindow)
        self.aLockMode.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("gui/icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aLockMode.setIcon(icon9)
        self.aLockMode.setObjectName("aLockMode")
        self.aShortcuts = QtGui.QAction(MainWindow)
        self.aShortcuts.setObjectName("aShortcuts")
        self.actionTraining = QtGui.QAction(MainWindow)
        self.actionTraining.setCheckable(True)
        self.actionTraining.setChecked(True)
        self.actionTraining.setObjectName("actionTraining")
        self.actionDefault_reace = QtGui.QAction(MainWindow)
        self.actionDefault_reace.setCheckable(True)
        self.actionDefault_reace.setObjectName("actionDefault_reace")
        self.actionKralovick_MTB_Maraton = QtGui.QAction(MainWindow)
        self.actionKralovick_MTB_Maraton.setCheckable(True)
        self.actionKralovick_MTB_Maraton.setObjectName("actionKralovick_MTB_Maraton")
        self.actionBliz_k_2011 = QtGui.QAction(MainWindow)
        self.actionBliz_k_2011.setCheckable(True)
        self.actionBliz_k_2011.setObjectName("actionBliz_k_2011")
        self.aDirectWwwExport = QtGui.QAction(MainWindow)
        self.aDirectWwwExport.setObjectName("aDirectWwwExport")
        self.aDirectExportCategories = QtGui.QAction(MainWindow)
        self.aDirectExportCategories.setObjectName("aDirectExportCategories")
        self.menuDatabase.addAction(self.actionLoad)
        self.menuDatabase.addAction(self.actionSave)
        self.menuDatabase.addAction(self.actionSave_As)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.aShortcuts)
        self.menuAbout.addAction(self.actionAbout)
        self.menuMode.addAction(self.actionTraining)
        self.menuMode.addSeparator()
        self.menuMode.addAction(self.actionDefault_reace)
        self.menuMode.addSeparator()
        self.menuMode.addAction(self.actionKralovick_MTB_Maraton)
        self.menuMode.addAction(self.actionBliz_k_2011)
        self.menuSettings.addAction(self.menuMode.menuAction())
        self.menuAction.addAction(self.aRefresh)
        self.menuAction.addAction(self.aDirectWwwExport)
        self.menuAction.addAction(self.aDirectExportCategories)
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar_Port.addAction(self.aSetPort)
        self.toolBar_Port.addSeparator()
        self.toolBar_Port.addAction(self.aConnectPort)
        self.toolBar_Action.addAction(self.aRefresh)
        self.toolBar_Modes.addAction(self.aRefreshMode)
        self.toolBar_Modes.addAction(self.aLockMode)
        self.toolBar_Modes.addAction(self.aEditMode)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EWITIS - Electronic Wireless Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.RunsFilterClear.setToolTip(QtGui.QApplication.translate("MainWindow", "Cancel filter", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesFilterClear.setToolTip(QtGui.QApplication.translate("MainWindow", "Cancel filter", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Add time", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove time(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesExport.setToolTip(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))        
        self.TimesWwwExport.setToolTip(QtGui.QApplication.translate("MainWindow", "WWW export", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear table", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesShowAll.setText(QtGui.QApplication.translate("MainWindow", "All Times", None, QtGui.QApplication.UnicodeUTF8))
        self.timesCounter.setText(QtGui.QApplication.translate("MainWindow", "16/187", None, QtGui.QApplication.UnicodeUTF8))
        self.timesShowZero.setText(QtGui.QApplication.translate("MainWindow", "Zero Times", None, QtGui.QApplication.UnicodeUTF8))
        self.RunsAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Add run", None, QtGui.QApplication.UnicodeUTF8))
        self.RunsRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove run(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.RunsExport.setToolTip(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.RunsDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear table", None, QtGui.QApplication.UnicodeUTF8))
        self.runsCounter.setText(QtGui.QApplication.translate("MainWindow", "16/187", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRuns_Times), QtGui.QApplication.translate("MainWindow", "Runs#Times", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersFilterClear.setToolTip(QtGui.QApplication.translate("MainWindow", "Cancel filter", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Add user", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove user(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersExport.setToolTip(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersImport.setToolTip(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear table", None, QtGui.QApplication.UnicodeUTF8))
        self.usersCounter.setText(QtGui.QApplication.translate("MainWindow", "16/187", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUsers), QtGui.QApplication.translate("MainWindow", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAction.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Port.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Action.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Modes.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.aSetPort.setText(QtGui.QApplication.translate("MainWindow", "PORT", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setToolTip(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefresh.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh (F5)", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefresh.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.aEditMode.setText(QtGui.QApplication.translate("MainWindow", "Editing mode", None, QtGui.QApplication.UnicodeUTF8))
        self.aEditMode.setToolTip(QtGui.QApplication.translate("MainWindow", "EDIT mode", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefreshMode.setText(QtGui.QApplication.translate("MainWindow", "Refreshing mode", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefreshMode.setToolTip(QtGui.QApplication.translate("MainWindow", "REFRESH mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As..", None, QtGui.QApplication.UnicodeUTF8))
        self.aLockMode.setText(QtGui.QApplication.translate("MainWindow", "Lock mode", None, QtGui.QApplication.UnicodeUTF8))
        self.aLockMode.setToolTip(QtGui.QApplication.translate("MainWindow", "LOCK mode", None, QtGui.QApplication.UnicodeUTF8))
        self.aShortcuts.setText(QtGui.QApplication.translate("MainWindow", "Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTraining.setText(QtGui.QApplication.translate("MainWindow", "Training", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_reace.setText(QtGui.QApplication.translate("MainWindow", "Race", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKralovick_MTB_Maraton.setText(QtGui.QApplication.translate("MainWindow", "Kralovický MTB Maraton", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBliz_k_2011.setText(QtGui.QApplication.translate("MainWindow", "Blizák 2011", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectWwwExport.setText(QtGui.QApplication.translate("MainWindow", "Direct Www Export", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectWwwExport.setToolTip(QtGui.QApplication.translate("MainWindow", "Direct WWW Export", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectWwwExport.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectExportCategories.setText(QtGui.QApplication.translate("MainWindow", "Direct Export Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectExportCategories.setToolTip(QtGui.QApplication.translate("MainWindow", "Direct Export Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectExportCategories.setShortcut(QtGui.QApplication.translate("MainWindow", "F12", None, QtGui.QApplication.UnicodeUTF8))

