# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ewitis_qt_template_v0_1.ui'
#
# Created: Tue Jun 26 18:55:12 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1117, 582)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRuns_Times = QtGui.QWidget()
        self.tabRuns_Times.setObjectName(_fromUtf8("tabRuns_Times"))
        self.gridLayout = QtGui.QGridLayout(self.tabRuns_Times)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.RunsFilterLineEdit = QtGui.QLineEdit(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.RunsFilterLineEdit.setSizePolicy(sizePolicy)
        self.RunsFilterLineEdit.setDragEnabled(False)
        self.RunsFilterLineEdit.setObjectName(_fromUtf8("RunsFilterLineEdit"))
        self.gridLayout.addWidget(self.RunsFilterLineEdit, 0, 0, 1, 1)
        self.RunsFilterClear = QtGui.QPushButton(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsFilterClear.sizePolicy().hasHeightForWidth())
        self.RunsFilterClear.setSizePolicy(sizePolicy)
        self.RunsFilterClear.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/mail-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsFilterClear.setIcon(icon)
        self.RunsFilterClear.setFlat(True)
        self.RunsFilterClear.setObjectName(_fromUtf8("RunsFilterClear"))
        self.gridLayout.addWidget(self.RunsFilterClear, 0, 1, 1, 1)
        self.RunsProxyView = QtGui.QTreeView(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsProxyView.sizePolicy().hasHeightForWidth())
        self.RunsProxyView.setSizePolicy(sizePolicy)
        self.RunsProxyView.setObjectName(_fromUtf8("RunsProxyView"))
        self.gridLayout.addWidget(self.RunsProxyView, 1, 0, 1, 4)
        self.runsCounter = QtGui.QLabel(self.tabRuns_Times)
        self.runsCounter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runsCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.runsCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runsCounter.setObjectName(_fromUtf8("runsCounter"))
        self.gridLayout.addWidget(self.runsCounter, 2, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.RunsAdd = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsAdd.sizePolicy().hasHeightForWidth())
        self.RunsAdd.setSizePolicy(sizePolicy)
        self.RunsAdd.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsAdd.setIcon(icon1)
        self.RunsAdd.setIconSize(QtCore.QSize(24, 24))
        self.RunsAdd.setAutoDefault(False)
        self.RunsAdd.setDefault(False)
        self.RunsAdd.setObjectName(_fromUtf8("RunsAdd"))
        self.horizontalLayout_2.addWidget(self.RunsAdd)
        self.RunsRemove = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsRemove.sizePolicy().hasHeightForWidth())
        self.RunsRemove.setSizePolicy(sizePolicy)
        self.RunsRemove.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsRemove.setIcon(icon2)
        self.RunsRemove.setIconSize(QtCore.QSize(24, 24))
        self.RunsRemove.setObjectName(_fromUtf8("RunsRemove"))
        self.horizontalLayout_2.addWidget(self.RunsRemove)
        self.RunsExport = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsExport.sizePolicy().hasHeightForWidth())
        self.RunsExport.setSizePolicy(sizePolicy)
        self.RunsExport.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsExport.setIcon(icon3)
        self.RunsExport.setIconSize(QtCore.QSize(24, 24))
        self.RunsExport.setObjectName(_fromUtf8("RunsExport"))
        self.horizontalLayout_2.addWidget(self.RunsExport)
        self.RunsDelete = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunsDelete.sizePolicy().hasHeightForWidth())
        self.RunsDelete.setSizePolicy(sizePolicy)
        self.RunsDelete.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/emptytrash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RunsDelete.setIcon(icon4)
        self.RunsDelete.setIconSize(QtCore.QSize(24, 24))
        self.RunsDelete.setObjectName(_fromUtf8("RunsDelete"))
        self.horizontalLayout_2.addWidget(self.RunsDelete)
        self.gridLayout.addWidget(self.groupBox_2, 0, 3, 1, 1)
        self.TimesShowAll = QtGui.QCheckBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesShowAll.sizePolicy().hasHeightForWidth())
        self.TimesShowAll.setSizePolicy(sizePolicy)
        self.TimesShowAll.setText(QtGui.QApplication.translate("MainWindow", "All Times", None, QtGui.QApplication.UnicodeUTF8))
        self.TimesShowAll.setObjectName(_fromUtf8("TimesShowAll"))
        self.gridLayout.addWidget(self.TimesShowAll, 0, 9, 1, 1)
        self.TimesFilterLineEdit = QtGui.QLineEdit(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.TimesFilterLineEdit.setSizePolicy(sizePolicy)
        self.TimesFilterLineEdit.setObjectName(_fromUtf8("TimesFilterLineEdit"))
        self.gridLayout.addWidget(self.TimesFilterLineEdit, 0, 5, 1, 1)
        self.TimesFilterClear = QtGui.QPushButton(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesFilterClear.sizePolicy().hasHeightForWidth())
        self.TimesFilterClear.setSizePolicy(sizePolicy)
        self.TimesFilterClear.setText(_fromUtf8(""))
        self.TimesFilterClear.setIcon(icon)
        self.TimesFilterClear.setFlat(True)
        self.TimesFilterClear.setObjectName(_fromUtf8("TimesFilterClear"))
        self.gridLayout.addWidget(self.TimesFilterClear, 0, 6, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.TimesAdd = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesAdd.sizePolicy().hasHeightForWidth())
        self.TimesAdd.setSizePolicy(sizePolicy)
        self.TimesAdd.setText(_fromUtf8(""))
        self.TimesAdd.setIcon(icon1)
        self.TimesAdd.setIconSize(QtCore.QSize(24, 24))
        self.TimesAdd.setAutoDefault(False)
        self.TimesAdd.setDefault(False)
        self.TimesAdd.setObjectName(_fromUtf8("TimesAdd"))
        self.horizontalLayout_3.addWidget(self.TimesAdd)
        self.TimesRemove = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesRemove.sizePolicy().hasHeightForWidth())
        self.TimesRemove.setSizePolicy(sizePolicy)
        self.TimesRemove.setText(_fromUtf8(""))
        self.TimesRemove.setIcon(icon2)
        self.TimesRemove.setIconSize(QtCore.QSize(24, 24))
        self.TimesRemove.setObjectName(_fromUtf8("TimesRemove"))
        self.horizontalLayout_3.addWidget(self.TimesRemove)
        self.TimesImport = QtGui.QPushButton(self.groupBox_3)
        self.TimesImport.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesImport.sizePolicy().hasHeightForWidth())
        self.TimesImport.setSizePolicy(sizePolicy)
        self.TimesImport.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesImport.setIcon(icon5)
        self.TimesImport.setIconSize(QtCore.QSize(24, 24))
        self.TimesImport.setObjectName(_fromUtf8("TimesImport"))
        self.horizontalLayout_3.addWidget(self.TimesImport)
        self.TimesExport = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesExport.sizePolicy().hasHeightForWidth())
        self.TimesExport.setSizePolicy(sizePolicy)
        self.TimesExport.setText(_fromUtf8(""))
        self.TimesExport.setIcon(icon3)
        self.TimesExport.setIconSize(QtCore.QSize(24, 24))
        self.TimesExport.setObjectName(_fromUtf8("TimesExport"))
        self.horizontalLayout_3.addWidget(self.TimesExport)
        self.TimesWwwExport = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesWwwExport.sizePolicy().hasHeightForWidth())
        self.TimesWwwExport.setSizePolicy(sizePolicy)
        self.TimesWwwExport.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/internet-web-browser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimesWwwExport.setIcon(icon6)
        self.TimesWwwExport.setIconSize(QtCore.QSize(24, 24))
        self.TimesWwwExport.setObjectName(_fromUtf8("TimesWwwExport"))
        self.horizontalLayout_3.addWidget(self.TimesWwwExport)
        self.TimesDelete = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesDelete.sizePolicy().hasHeightForWidth())
        self.TimesDelete.setSizePolicy(sizePolicy)
        self.TimesDelete.setText(_fromUtf8(""))
        self.TimesDelete.setIcon(icon4)
        self.TimesDelete.setIconSize(QtCore.QSize(24, 24))
        self.TimesDelete.setObjectName(_fromUtf8("TimesDelete"))
        self.horizontalLayout_3.addWidget(self.TimesDelete)
        self.gridLayout.addWidget(self.groupBox_3, 0, 11, 1, 1)
        self.TimesProxyView = QtGui.QTreeView(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesProxyView.sizePolicy().hasHeightForWidth())
        self.TimesProxyView.setSizePolicy(sizePolicy)
        self.TimesProxyView.setObjectName(_fromUtf8("TimesProxyView"))
        self.gridLayout.addWidget(self.TimesProxyView, 1, 5, 1, 7)
        self.timesShowZero = QtGui.QCheckBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timesShowZero.sizePolicy().hasHeightForWidth())
        self.timesShowZero.setSizePolicy(sizePolicy)
        self.timesShowZero.setText(QtGui.QApplication.translate("MainWindow", "Zero Times", None, QtGui.QApplication.UnicodeUTF8))
        self.timesShowZero.setChecked(True)
        self.timesShowZero.setObjectName(_fromUtf8("timesShowZero"))
        self.gridLayout.addWidget(self.timesShowZero, 0, 8, 1, 1)
        self.timesCounter = QtGui.QLabel(self.tabRuns_Times)
        self.timesCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.timesCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timesCounter.setObjectName(_fromUtf8("timesCounter"))
        self.gridLayout.addWidget(self.timesCounter, 2, 11, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 7, 1, 1)
        self.timesAdditionalInfo = QtGui.QCheckBox(self.tabRuns_Times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timesAdditionalInfo.sizePolicy().hasHeightForWidth())
        self.timesAdditionalInfo.setSizePolicy(sizePolicy)
        self.timesAdditionalInfo.setText(QtGui.QApplication.translate("MainWindow", "Aditinal Info", None, QtGui.QApplication.UnicodeUTF8))
        self.timesAdditionalInfo.setObjectName(_fromUtf8("timesAdditionalInfo"))
        self.gridLayout.addWidget(self.timesAdditionalInfo, 0, 10, 1, 1)
        self.tabWidget.addTab(self.tabRuns_Times, _fromUtf8(""))
        self.tabUsers = QtGui.QWidget()
        self.tabUsers.setObjectName(_fromUtf8("tabUsers"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabUsers)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.UsersFilterLineEdit = QtGui.QLineEdit(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.UsersFilterLineEdit.setSizePolicy(sizePolicy)
        self.UsersFilterLineEdit.setObjectName(_fromUtf8("UsersFilterLineEdit"))
        self.gridLayout_3.addWidget(self.UsersFilterLineEdit, 0, 0, 1, 1)
        self.UsersFilterClear = QtGui.QPushButton(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersFilterClear.sizePolicy().hasHeightForWidth())
        self.UsersFilterClear.setSizePolicy(sizePolicy)
        self.UsersFilterClear.setText(_fromUtf8(""))
        self.UsersFilterClear.setIcon(icon)
        self.UsersFilterClear.setAutoRepeat(False)
        self.UsersFilterClear.setFlat(True)
        self.UsersFilterClear.setObjectName(_fromUtf8("UsersFilterClear"))
        self.gridLayout_3.addWidget(self.UsersFilterClear, 0, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.UsersAdd = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersAdd.sizePolicy().hasHeightForWidth())
        self.UsersAdd.setSizePolicy(sizePolicy)
        self.UsersAdd.setText(_fromUtf8(""))
        self.UsersAdd.setIcon(icon1)
        self.UsersAdd.setIconSize(QtCore.QSize(24, 24))
        self.UsersAdd.setAutoDefault(False)
        self.UsersAdd.setDefault(False)
        self.UsersAdd.setObjectName(_fromUtf8("UsersAdd"))
        self.horizontalLayout_9.addWidget(self.UsersAdd)
        self.UsersRemove = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersRemove.sizePolicy().hasHeightForWidth())
        self.UsersRemove.setSizePolicy(sizePolicy)
        self.UsersRemove.setText(_fromUtf8(""))
        self.UsersRemove.setIcon(icon2)
        self.UsersRemove.setIconSize(QtCore.QSize(24, 24))
        self.UsersRemove.setObjectName(_fromUtf8("UsersRemove"))
        self.horizontalLayout_9.addWidget(self.UsersRemove)
        self.UsersImport = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersImport.sizePolicy().hasHeightForWidth())
        self.UsersImport.setSizePolicy(sizePolicy)
        self.UsersImport.setText(_fromUtf8(""))
        self.UsersImport.setIcon(icon5)
        self.UsersImport.setIconSize(QtCore.QSize(24, 24))
        self.UsersImport.setObjectName(_fromUtf8("UsersImport"))
        self.horizontalLayout_9.addWidget(self.UsersImport)
        self.UsersExport = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersExport.sizePolicy().hasHeightForWidth())
        self.UsersExport.setSizePolicy(sizePolicy)
        self.UsersExport.setText(_fromUtf8(""))
        self.UsersExport.setIcon(icon3)
        self.UsersExport.setIconSize(QtCore.QSize(24, 24))
        self.UsersExport.setObjectName(_fromUtf8("UsersExport"))
        self.horizontalLayout_9.addWidget(self.UsersExport)
        self.UsersDelete = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersDelete.sizePolicy().hasHeightForWidth())
        self.UsersDelete.setSizePolicy(sizePolicy)
        self.UsersDelete.setText(_fromUtf8(""))
        self.UsersDelete.setIcon(icon4)
        self.UsersDelete.setIconSize(QtCore.QSize(24, 24))
        self.UsersDelete.setObjectName(_fromUtf8("UsersDelete"))
        self.horizontalLayout_9.addWidget(self.UsersDelete)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 3, 1, 1)
        self.UsersProxyView = QtGui.QTreeView(self.tabUsers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersProxyView.sizePolicy().hasHeightForWidth())
        self.UsersProxyView.setSizePolicy(sizePolicy)
        self.UsersProxyView.setObjectName(_fromUtf8("UsersProxyView"))
        self.gridLayout_3.addWidget(self.UsersProxyView, 1, 0, 1, 4)
        self.UsersCounter = QtGui.QLabel(self.tabUsers)
        self.UsersCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.UsersCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UsersCounter.setObjectName(_fromUtf8("UsersCounter"))
        self.gridLayout_3.addWidget(self.UsersCounter, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabUsers, _fromUtf8(""))
        self.tabCategories = QtGui.QWidget()
        self.tabCategories.setObjectName(_fromUtf8("tabCategories"))
        self.gridLayout_31 = QtGui.QGridLayout(self.tabCategories)
        self.gridLayout_31.setHorizontalSpacing(0)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.CategoriesFilterLineEdit = QtGui.QLineEdit(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.CategoriesFilterLineEdit.setSizePolicy(sizePolicy)
        self.CategoriesFilterLineEdit.setObjectName(_fromUtf8("CategoriesFilterLineEdit"))
        self.gridLayout_31.addWidget(self.CategoriesFilterLineEdit, 0, 0, 1, 1)
        self.CategoriesFilterClear = QtGui.QPushButton(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesFilterClear.sizePolicy().hasHeightForWidth())
        self.CategoriesFilterClear.setSizePolicy(sizePolicy)
        self.CategoriesFilterClear.setText(_fromUtf8(""))
        self.CategoriesFilterClear.setIcon(icon)
        self.CategoriesFilterClear.setAutoRepeat(False)
        self.CategoriesFilterClear.setFlat(True)
        self.CategoriesFilterClear.setObjectName(_fromUtf8("CategoriesFilterClear"))
        self.gridLayout_31.addWidget(self.CategoriesFilterClear, 0, 1, 1, 1)
        self.groupBox_51 = QtGui.QGroupBox(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_51.sizePolicy().hasHeightForWidth())
        self.groupBox_51.setSizePolicy(sizePolicy)
        self.groupBox_51.setTitle(_fromUtf8(""))
        self.groupBox_51.setObjectName(_fromUtf8("groupBox_51"))
        self.horizontalLayout_91 = QtGui.QHBoxLayout(self.groupBox_51)
        self.horizontalLayout_91.setSpacing(0)
        self.horizontalLayout_91.setMargin(0)
        self.horizontalLayout_91.setObjectName(_fromUtf8("horizontalLayout_91"))
        self.CategoriesAdd = QtGui.QPushButton(self.groupBox_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesAdd.sizePolicy().hasHeightForWidth())
        self.CategoriesAdd.setSizePolicy(sizePolicy)
        self.CategoriesAdd.setText(_fromUtf8(""))
        self.CategoriesAdd.setIcon(icon1)
        self.CategoriesAdd.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesAdd.setAutoDefault(False)
        self.CategoriesAdd.setDefault(False)
        self.CategoriesAdd.setObjectName(_fromUtf8("CategoriesAdd"))
        self.horizontalLayout_91.addWidget(self.CategoriesAdd)
        self.CategoriesRemove = QtGui.QPushButton(self.groupBox_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesRemove.sizePolicy().hasHeightForWidth())
        self.CategoriesRemove.setSizePolicy(sizePolicy)
        self.CategoriesRemove.setText(_fromUtf8(""))
        self.CategoriesRemove.setIcon(icon2)
        self.CategoriesRemove.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesRemove.setObjectName(_fromUtf8("CategoriesRemove"))
        self.horizontalLayout_91.addWidget(self.CategoriesRemove)
        self.CategoriesImport = QtGui.QPushButton(self.groupBox_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesImport.sizePolicy().hasHeightForWidth())
        self.CategoriesImport.setSizePolicy(sizePolicy)
        self.CategoriesImport.setText(_fromUtf8(""))
        self.CategoriesImport.setIcon(icon5)
        self.CategoriesImport.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesImport.setObjectName(_fromUtf8("CategoriesImport"))
        self.horizontalLayout_91.addWidget(self.CategoriesImport)
        self.CategoriesExport = QtGui.QPushButton(self.groupBox_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesExport.sizePolicy().hasHeightForWidth())
        self.CategoriesExport.setSizePolicy(sizePolicy)
        self.CategoriesExport.setText(_fromUtf8(""))
        self.CategoriesExport.setIcon(icon3)
        self.CategoriesExport.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesExport.setObjectName(_fromUtf8("CategoriesExport"))
        self.horizontalLayout_91.addWidget(self.CategoriesExport)
        self.CategoriesDelete = QtGui.QPushButton(self.groupBox_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesDelete.sizePolicy().hasHeightForWidth())
        self.CategoriesDelete.setSizePolicy(sizePolicy)
        self.CategoriesDelete.setText(_fromUtf8(""))
        self.CategoriesDelete.setIcon(icon4)
        self.CategoriesDelete.setIconSize(QtCore.QSize(24, 24))
        self.CategoriesDelete.setObjectName(_fromUtf8("CategoriesDelete"))
        self.horizontalLayout_91.addWidget(self.CategoriesDelete)
        self.gridLayout_31.addWidget(self.groupBox_51, 0, 3, 1, 1)
        self.CategoriesProxyView = QtGui.QTreeView(self.tabCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoriesProxyView.sizePolicy().hasHeightForWidth())
        self.CategoriesProxyView.setSizePolicy(sizePolicy)
        self.CategoriesProxyView.setObjectName(_fromUtf8("CategoriesProxyView"))
        self.gridLayout_31.addWidget(self.CategoriesProxyView, 1, 0, 1, 4)
        self.CategoriesCounter = QtGui.QLabel(self.tabCategories)
        self.CategoriesCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.CategoriesCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CategoriesCounter.setObjectName(_fromUtf8("CategoriesCounter"))
        self.gridLayout_31.addWidget(self.CategoriesCounter, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabCategories, _fromUtf8(""))
        self.tabCGroups = QtGui.QWidget()
        self.tabCGroups.setObjectName(_fromUtf8("tabCGroups"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabCGroups)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.CGroupsFilterLineEdit = QtGui.QLineEdit(self.tabCGroups)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.CGroupsFilterLineEdit.setSizePolicy(sizePolicy)
        self.CGroupsFilterLineEdit.setObjectName(_fromUtf8("CGroupsFilterLineEdit"))
        self.gridLayout_2.addWidget(self.CGroupsFilterLineEdit, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.tabCGroups)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.CGroupsAdd = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsAdd.sizePolicy().hasHeightForWidth())
        self.CGroupsAdd.setSizePolicy(sizePolicy)
        self.CGroupsAdd.setText(_fromUtf8(""))
        self.CGroupsAdd.setIcon(icon1)
        self.CGroupsAdd.setIconSize(QtCore.QSize(24, 24))
        self.CGroupsAdd.setAutoDefault(False)
        self.CGroupsAdd.setDefault(False)
        self.CGroupsAdd.setObjectName(_fromUtf8("CGroupsAdd"))
        self.horizontalLayout_12.addWidget(self.CGroupsAdd)
        self.CGroupsRemove = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsRemove.sizePolicy().hasHeightForWidth())
        self.CGroupsRemove.setSizePolicy(sizePolicy)
        self.CGroupsRemove.setText(_fromUtf8(""))
        self.CGroupsRemove.setIcon(icon2)
        self.CGroupsRemove.setIconSize(QtCore.QSize(24, 24))
        self.CGroupsRemove.setObjectName(_fromUtf8("CGroupsRemove"))
        self.horizontalLayout_12.addWidget(self.CGroupsRemove)
        self.CGroupsImport = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsImport.sizePolicy().hasHeightForWidth())
        self.CGroupsImport.setSizePolicy(sizePolicy)
        self.CGroupsImport.setText(_fromUtf8(""))
        self.CGroupsImport.setIcon(icon5)
        self.CGroupsImport.setIconSize(QtCore.QSize(24, 24))
        self.CGroupsImport.setObjectName(_fromUtf8("CGroupsImport"))
        self.horizontalLayout_12.addWidget(self.CGroupsImport)
        self.CGroupsExport = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsExport.sizePolicy().hasHeightForWidth())
        self.CGroupsExport.setSizePolicy(sizePolicy)
        self.CGroupsExport.setText(_fromUtf8(""))
        self.CGroupsExport.setIcon(icon3)
        self.CGroupsExport.setIconSize(QtCore.QSize(24, 24))
        self.CGroupsExport.setObjectName(_fromUtf8("CGroupsExport"))
        self.horizontalLayout_12.addWidget(self.CGroupsExport)
        self.CGroupsDelete = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsDelete.sizePolicy().hasHeightForWidth())
        self.CGroupsDelete.setSizePolicy(sizePolicy)
        self.CGroupsDelete.setText(_fromUtf8(""))
        self.CGroupsDelete.setIcon(icon4)
        self.CGroupsDelete.setIconSize(QtCore.QSize(24, 24))
        self.CGroupsDelete.setObjectName(_fromUtf8("CGroupsDelete"))
        self.horizontalLayout_12.addWidget(self.CGroupsDelete)
        self.gridLayout_2.addWidget(self.groupBox_8, 0, 3, 1, 1)
        self.CGroupsProxyView = QtGui.QTreeView(self.tabCGroups)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsProxyView.sizePolicy().hasHeightForWidth())
        self.CGroupsProxyView.setSizePolicy(sizePolicy)
        self.CGroupsProxyView.setObjectName(_fromUtf8("CGroupsProxyView"))
        self.gridLayout_2.addWidget(self.CGroupsProxyView, 1, 0, 1, 4)
        self.CGroupsCounter = QtGui.QLabel(self.tabCGroups)
        self.CGroupsCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.CGroupsCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CGroupsCounter.setObjectName(_fromUtf8("CGroupsCounter"))
        self.gridLayout_2.addWidget(self.CGroupsCounter, 2, 3, 1, 1)
        self.CGroupsFilterClear = QtGui.QPushButton(self.tabCGroups)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGroupsFilterClear.sizePolicy().hasHeightForWidth())
        self.CGroupsFilterClear.setSizePolicy(sizePolicy)
        self.CGroupsFilterClear.setText(_fromUtf8(""))
        self.CGroupsFilterClear.setIcon(icon)
        self.CGroupsFilterClear.setAutoRepeat(False)
        self.CGroupsFilterClear.setFlat(True)
        self.CGroupsFilterClear.setObjectName(_fromUtf8("CGroupsFilterClear"))
        self.gridLayout_2.addWidget(self.CGroupsFilterClear, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabCGroups, _fromUtf8(""))
        self.tabTags = QtGui.QWidget()
        self.tabTags.setObjectName(_fromUtf8("tabTags"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabTags)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.TagsProxyView = QtGui.QTreeView(self.tabTags)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsProxyView.sizePolicy().hasHeightForWidth())
        self.TagsProxyView.setSizePolicy(sizePolicy)
        self.TagsProxyView.setObjectName(_fromUtf8("TagsProxyView"))
        self.gridLayout_4.addWidget(self.TagsProxyView, 3, 0, 1, 4)
        self.TagsFilterLineEdit = QtGui.QLineEdit(self.tabTags)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.TagsFilterLineEdit.setSizePolicy(sizePolicy)
        self.TagsFilterLineEdit.setObjectName(_fromUtf8("TagsFilterLineEdit"))
        self.gridLayout_4.addWidget(self.TagsFilterLineEdit, 2, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tabTags)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.TagsAdd = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsAdd.sizePolicy().hasHeightForWidth())
        self.TagsAdd.setSizePolicy(sizePolicy)
        self.TagsAdd.setText(_fromUtf8(""))
        self.TagsAdd.setIcon(icon1)
        self.TagsAdd.setIconSize(QtCore.QSize(24, 24))
        self.TagsAdd.setAutoDefault(False)
        self.TagsAdd.setDefault(False)
        self.TagsAdd.setObjectName(_fromUtf8("TagsAdd"))
        self.horizontalLayout_11.addWidget(self.TagsAdd)
        self.TagsRemove = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsRemove.sizePolicy().hasHeightForWidth())
        self.TagsRemove.setSizePolicy(sizePolicy)
        self.TagsRemove.setText(_fromUtf8(""))
        self.TagsRemove.setIcon(icon2)
        self.TagsRemove.setIconSize(QtCore.QSize(24, 24))
        self.TagsRemove.setObjectName(_fromUtf8("TagsRemove"))
        self.horizontalLayout_11.addWidget(self.TagsRemove)
        self.TagsImport = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsImport.sizePolicy().hasHeightForWidth())
        self.TagsImport.setSizePolicy(sizePolicy)
        self.TagsImport.setText(_fromUtf8(""))
        self.TagsImport.setIcon(icon5)
        self.TagsImport.setIconSize(QtCore.QSize(24, 24))
        self.TagsImport.setObjectName(_fromUtf8("TagsImport"))
        self.horizontalLayout_11.addWidget(self.TagsImport)
        self.TagsExport = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsExport.sizePolicy().hasHeightForWidth())
        self.TagsExport.setSizePolicy(sizePolicy)
        self.TagsExport.setText(_fromUtf8(""))
        self.TagsExport.setIcon(icon3)
        self.TagsExport.setIconSize(QtCore.QSize(24, 24))
        self.TagsExport.setObjectName(_fromUtf8("TagsExport"))
        self.horizontalLayout_11.addWidget(self.TagsExport)
        self.TagsDelete = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsDelete.sizePolicy().hasHeightForWidth())
        self.TagsDelete.setSizePolicy(sizePolicy)
        self.TagsDelete.setText(_fromUtf8(""))
        self.TagsDelete.setIcon(icon4)
        self.TagsDelete.setIconSize(QtCore.QSize(24, 24))
        self.TagsDelete.setObjectName(_fromUtf8("TagsDelete"))
        self.horizontalLayout_11.addWidget(self.TagsDelete)
        self.gridLayout_4.addWidget(self.groupBox_7, 2, 3, 1, 1)
        self.TagsCounter = QtGui.QLabel(self.tabTags)
        self.TagsCounter.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.TagsCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TagsCounter.setObjectName(_fromUtf8("TagsCounter"))
        self.gridLayout_4.addWidget(self.TagsCounter, 4, 3, 1, 1)
        self.TagsFilterClear = QtGui.QPushButton(self.tabTags)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagsFilterClear.sizePolicy().hasHeightForWidth())
        self.TagsFilterClear.setSizePolicy(sizePolicy)
        self.TagsFilterClear.setText(_fromUtf8(""))
        self.TagsFilterClear.setIcon(icon)
        self.TagsFilterClear.setAutoRepeat(False)
        self.TagsFilterClear.setFlat(True)
        self.TagsFilterClear.setObjectName(_fromUtf8("TagsFilterClear"))
        self.gridLayout_4.addWidget(self.TagsFilterClear, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tabTags, _fromUtf8(""))
        self.tabTerminal = QtGui.QWidget()
        self.tabTerminal.setObjectName(_fromUtf8("tabTerminal"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabTerminal)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupTerminal = QtGui.QGroupBox(self.tabTerminal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupTerminal.sizePolicy().hasHeightForWidth())
        self.groupTerminal.setSizePolicy(sizePolicy)
        self.groupTerminal.setMinimumSize(QtCore.QSize(350, 0))
        self.groupTerminal.setAutoFillBackground(False)
        self.groupTerminal.setTitle(QtGui.QApplication.translate("MainWindow", "T E R M I N Á L", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTerminal.setObjectName(_fromUtf8("groupTerminal"))
        self.label = QtGui.QLabel(self.groupTerminal)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Nr. of cells :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupTerminal)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Battery :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupTerminal)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Backlight :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupTerminal)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Speaker :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupTerminal)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Language :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupTerminal)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Time :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineCells = QtGui.QLineEdit(self.groupTerminal)
        self.lineCells.setEnabled(True)
        self.lineCells.setGeometry(QtCore.QRect(100, 40, 31, 20))
        self.lineCells.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineCells.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.lineCells.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCells.setReadOnly(True)
        self.lineCells.setObjectName(_fromUtf8("lineCells"))
        self.lineBattery = QtGui.QLineEdit(self.groupTerminal)
        self.lineBattery.setGeometry(QtCore.QRect(100, 70, 41, 20))
        self.lineBattery.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineBattery.setText(QtGui.QApplication.translate("MainWindow", "- - ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineBattery.setAlignment(QtCore.Qt.AlignCenter)
        self.lineBattery.setReadOnly(True)
        self.lineBattery.setObjectName(_fromUtf8("lineBattery"))
        self.dateDate = QtGui.QDateEdit(self.groupTerminal)
        self.dateDate.setGeometry(QtCore.QRect(180, 310, 71, 22))
        self.dateDate.setDate(QtCore.QDate(1900, 1, 1))
        self.dateDate.setObjectName(_fromUtf8("dateDate"))
        self.timeTime = QtGui.QTimeEdit(self.groupTerminal)
        self.timeTime.setGeometry(QtCore.QRect(180, 280, 71, 22))
        self.timeTime.setObjectName(_fromUtf8("timeTime"))
        self.pushBacklight = QtGui.QPushButton(self.groupTerminal)
        self.pushBacklight.setEnabled(True)
        self.pushBacklight.setGeometry(QtCore.QRect(180, 100, 41, 21))
        self.pushBacklight.setAutoFillBackground(False)
        self.pushBacklight.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBacklight.setAutoDefault(False)
        self.pushBacklight.setDefault(False)
        self.pushBacklight.setFlat(False)
        self.pushBacklight.setObjectName(_fromUtf8("pushBacklight"))
        self.label_7 = QtGui.QLabel(self.groupTerminal)
        self.label_7.setGeometry(QtCore.QRect(40, 150, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Keys :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupTerminal)
        self.label_8.setGeometry(QtCore.QRect(40, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "System :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupTerminal)
        self.label_9.setGeometry(QtCore.QRect(40, 210, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Timing :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboLanguage = QtGui.QComboBox(self.groupTerminal)
        self.comboLanguage.setGeometry(QtCore.QRect(180, 250, 69, 22))
        self.comboLanguage.setObjectName(_fromUtf8("comboLanguage"))
        self.comboLanguage.addItem(_fromUtf8(""))
        self.comboLanguage.setItemText(0, QtGui.QApplication.translate("MainWindow", "čeština", None, QtGui.QApplication.UnicodeUTF8))
        self.comboLanguage.addItem(_fromUtf8(""))
        self.comboLanguage.setItemText(1, QtGui.QApplication.translate("MainWindow", "english", None, QtGui.QApplication.UnicodeUTF8))
        self.lineBacklight = QtGui.QLineEdit(self.groupTerminal)
        self.lineBacklight.setGeometry(QtCore.QRect(100, 100, 41, 20))
        self.lineBacklight.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineBacklight.setAutoFillBackground(False)
        self.lineBacklight.setStyleSheet(_fromUtf8(""))
        self.lineBacklight.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineBacklight.setAlignment(QtCore.Qt.AlignCenter)
        self.lineBacklight.setReadOnly(True)
        self.lineBacklight.setObjectName(_fromUtf8("lineBacklight"))
        self.lineSpeakerKeys = QtGui.QLineEdit(self.groupTerminal)
        self.lineSpeakerKeys.setGeometry(QtCore.QRect(100, 150, 41, 20))
        self.lineSpeakerKeys.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineSpeakerKeys.setAutoFillBackground(False)
        self.lineSpeakerKeys.setStyleSheet(_fromUtf8(""))
        self.lineSpeakerKeys.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpeakerKeys.setAlignment(QtCore.Qt.AlignCenter)
        self.lineSpeakerKeys.setReadOnly(True)
        self.lineSpeakerKeys.setObjectName(_fromUtf8("lineSpeakerKeys"))
        self.pushSpeakerKeys = QtGui.QPushButton(self.groupTerminal)
        self.pushSpeakerKeys.setEnabled(True)
        self.pushSpeakerKeys.setGeometry(QtCore.QRect(180, 150, 41, 21))
        self.pushSpeakerKeys.setAutoFillBackground(False)
        self.pushSpeakerKeys.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSpeakerKeys.setAutoDefault(False)
        self.pushSpeakerKeys.setDefault(False)
        self.pushSpeakerKeys.setFlat(False)
        self.pushSpeakerKeys.setObjectName(_fromUtf8("pushSpeakerKeys"))
        self.pushSpeakerSystem = QtGui.QPushButton(self.groupTerminal)
        self.pushSpeakerSystem.setEnabled(True)
        self.pushSpeakerSystem.setGeometry(QtCore.QRect(180, 180, 41, 21))
        self.pushSpeakerSystem.setAutoFillBackground(False)
        self.pushSpeakerSystem.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSpeakerSystem.setAutoDefault(False)
        self.pushSpeakerSystem.setDefault(False)
        self.pushSpeakerSystem.setFlat(False)
        self.pushSpeakerSystem.setObjectName(_fromUtf8("pushSpeakerSystem"))
        self.lineSpeakerSystem = QtGui.QLineEdit(self.groupTerminal)
        self.lineSpeakerSystem.setGeometry(QtCore.QRect(100, 180, 41, 20))
        self.lineSpeakerSystem.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineSpeakerSystem.setAutoFillBackground(False)
        self.lineSpeakerSystem.setStyleSheet(_fromUtf8(""))
        self.lineSpeakerSystem.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpeakerSystem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineSpeakerSystem.setReadOnly(True)
        self.lineSpeakerSystem.setObjectName(_fromUtf8("lineSpeakerSystem"))
        self.pushSpeakerTiming = QtGui.QPushButton(self.groupTerminal)
        self.pushSpeakerTiming.setEnabled(True)
        self.pushSpeakerTiming.setGeometry(QtCore.QRect(180, 210, 41, 21))
        self.pushSpeakerTiming.setAutoFillBackground(False)
        self.pushSpeakerTiming.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSpeakerTiming.setAutoDefault(False)
        self.pushSpeakerTiming.setDefault(False)
        self.pushSpeakerTiming.setFlat(False)
        self.pushSpeakerTiming.setObjectName(_fromUtf8("pushSpeakerTiming"))
        self.lineSpeakerTiming = QtGui.QLineEdit(self.groupTerminal)
        self.lineSpeakerTiming.setGeometry(QtCore.QRect(100, 210, 41, 20))
        self.lineSpeakerTiming.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineSpeakerTiming.setAutoFillBackground(False)
        self.lineSpeakerTiming.setStyleSheet(_fromUtf8(""))
        self.lineSpeakerTiming.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpeakerTiming.setAlignment(QtCore.Qt.AlignCenter)
        self.lineSpeakerTiming.setReadOnly(True)
        self.lineSpeakerTiming.setObjectName(_fromUtf8("lineSpeakerTiming"))
        self.lineLanguage = QtGui.QLineEdit(self.groupTerminal)
        self.lineLanguage.setGeometry(QtCore.QRect(100, 250, 61, 20))
        self.lineLanguage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineLanguage.setAutoFillBackground(False)
        self.lineLanguage.setStyleSheet(_fromUtf8(""))
        self.lineLanguage.setText(QtGui.QApplication.translate("MainWindow", "- - -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineLanguage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineLanguage.setReadOnly(True)
        self.lineLanguage.setObjectName(_fromUtf8("lineLanguage"))
        self.lineTime = QtGui.QLineEdit(self.groupTerminal)
        self.lineTime.setGeometry(QtCore.QRect(100, 280, 61, 20))
        self.lineTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineTime.setAutoFillBackground(False)
        self.lineTime.setStyleSheet(_fromUtf8(""))
        self.lineTime.setText(QtGui.QApplication.translate("MainWindow", "- - -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineTime.setReadOnly(True)
        self.lineTime.setObjectName(_fromUtf8("lineTime"))
        self.lineDate = QtGui.QLineEdit(self.groupTerminal)
        self.lineDate.setGeometry(QtCore.QRect(100, 310, 61, 20))
        self.lineDate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineDate.setAutoFillBackground(False)
        self.lineDate.setStyleSheet(_fromUtf8(""))
        self.lineDate.setText(QtGui.QApplication.translate("MainWindow", "- - -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineDate.setReadOnly(True)
        self.lineDate.setObjectName(_fromUtf8("lineDate"))
        self.label_12 = QtGui.QLabel(self.groupTerminal)
        self.label_12.setGeometry(QtCore.QRect(20, 310, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushSpeakerKeys_3 = QtGui.QPushButton(self.groupTerminal)
        self.pushSpeakerKeys_3.setEnabled(True)
        self.pushSpeakerKeys_3.setGeometry(QtCore.QRect(260, 280, 41, 21))
        self.pushSpeakerKeys_3.setAutoFillBackground(False)
        self.pushSpeakerKeys_3.setText(QtGui.QApplication.translate("MainWindow", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSpeakerKeys_3.setAutoDefault(False)
        self.pushSpeakerKeys_3.setDefault(False)
        self.pushSpeakerKeys_3.setFlat(False)
        self.pushSpeakerKeys_3.setObjectName(_fromUtf8("pushSpeakerKeys_3"))
        self.pushSpeakerKeys_4 = QtGui.QPushButton(self.groupTerminal)
        self.pushSpeakerKeys_4.setEnabled(True)
        self.pushSpeakerKeys_4.setGeometry(QtCore.QRect(260, 310, 41, 21))
        self.pushSpeakerKeys_4.setAutoFillBackground(False)
        self.pushSpeakerKeys_4.setText(QtGui.QApplication.translate("MainWindow", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSpeakerKeys_4.setAutoDefault(False)
        self.pushSpeakerKeys_4.setDefault(False)
        self.pushSpeakerKeys_4.setFlat(False)
        self.pushSpeakerKeys_4.setObjectName(_fromUtf8("pushSpeakerKeys_4"))
        self.pushSpeakerKeys_5 = QtGui.QPushButton(self.groupTerminal)
        self.pushSpeakerKeys_5.setEnabled(True)
        self.pushSpeakerKeys_5.setGeometry(QtCore.QRect(180, 340, 131, 21))
        self.pushSpeakerKeys_5.setAutoFillBackground(False)
        self.pushSpeakerKeys_5.setText(QtGui.QApplication.translate("MainWindow", "FILL CURRENT DATETIME", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSpeakerKeys_5.setAutoDefault(False)
        self.pushSpeakerKeys_5.setDefault(False)
        self.pushSpeakerKeys_5.setFlat(False)
        self.pushSpeakerKeys_5.setObjectName(_fromUtf8("pushSpeakerKeys_5"))
        self.gridLayout_5.addWidget(self.groupTerminal, 0, 0, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.tabTerminal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "CELL #1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Battery :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineBattery_2 = QtGui.QLineEdit(self.groupBox)
        self.lineBattery_2.setGeometry(QtCore.QRect(90, 30, 41, 20))
        self.lineBattery_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineBattery_2.setText(QtGui.QApplication.translate("MainWindow", "100 %", None, QtGui.QApplication.UnicodeUTF8))
        self.lineBattery_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineBattery_2.setReadOnly(True)
        self.lineBattery_2.setObjectName(_fromUtf8("lineBattery_2"))
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tabTerminal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "CELL #2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Battery :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineBattery_3 = QtGui.QLineEdit(self.groupBox_6)
        self.lineBattery_3.setGeometry(QtCore.QRect(90, 30, 41, 20))
        self.lineBattery_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineBattery_3.setText(QtGui.QApplication.translate("MainWindow", "100 %", None, QtGui.QApplication.UnicodeUTF8))
        self.lineBattery_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineBattery_3.setReadOnly(True)
        self.lineBattery_3.setObjectName(_fromUtf8("lineBattery_3"))
        self.gridLayout_5.addWidget(self.groupBox_6, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabTerminal, _fromUtf8(""))
        self.tabTimingSettings = QtGui.QWidget()
        self.tabTimingSettings.setObjectName(_fromUtf8("tabTimingSettings"))
        self.groupTerminal_2 = QtGui.QGroupBox(self.tabTimingSettings)
        self.groupTerminal_2.setGeometry(QtCore.QRect(30, 30, 301, 381))
        self.groupTerminal_2.setAutoFillBackground(False)
        self.groupTerminal_2.setTitle(QtGui.QApplication.translate("MainWindow", "T I M I N G   M O D E", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTerminal_2.setObjectName(_fromUtf8("groupTerminal_2"))
        self.comboTimingMode = QtGui.QComboBox(self.groupTerminal_2)
        self.comboTimingMode.setGeometry(QtCore.QRect(170, 35, 91, 20))
        self.comboTimingMode.setObjectName(_fromUtf8("comboTimingMode"))
        self.comboTimingMode.addItem(_fromUtf8(""))
        self.comboTimingMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "basic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTimingMode.addItem(_fromUtf8(""))
        self.comboTimingMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "manual", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTimingMode.addItem(_fromUtf8(""))
        self.comboTimingMode.setItemText(2, QtGui.QApplication.translate("MainWindow", "single start", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTimingMode.addItem(_fromUtf8(""))
        self.comboTimingMode.setItemText(3, QtGui.QApplication.translate("MainWindow", "multiple start", None, QtGui.QApplication.UnicodeUTF8))
        self.lineTimingMode = QtGui.QLineEdit(self.groupTerminal_2)
        self.lineTimingMode.setGeometry(QtCore.QRect(20, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineTimingMode.setFont(font)
        self.lineTimingMode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineTimingMode.setAutoFillBackground(False)
        self.lineTimingMode.setStyleSheet(_fromUtf8(""))
        self.lineTimingMode.setText(QtGui.QApplication.translate("MainWindow", "Multiple", None, QtGui.QApplication.UnicodeUTF8))
        self.lineTimingMode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineTimingMode.setReadOnly(True)
        self.lineTimingMode.setObjectName(_fromUtf8("lineTimingMode"))
        self.spinTagtime = QtGui.QSpinBox(self.groupTerminal_2)
        self.spinTagtime.setGeometry(QtCore.QRect(230, 150, 61, 22))
        self.spinTagtime.setMaximum(255)
        self.spinTagtime.setObjectName(_fromUtf8("spinTagtime"))
        self.lineFilterTagtime = QtGui.QLineEdit(self.groupTerminal_2)
        self.lineFilterTagtime.setGeometry(QtCore.QRect(170, 150, 41, 20))
        self.lineFilterTagtime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineFilterTagtime.setAutoFillBackground(False)
        self.lineFilterTagtime.setStyleSheet(_fromUtf8(""))
        self.lineFilterTagtime.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineFilterTagtime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineFilterTagtime.setReadOnly(True)
        self.lineFilterTagtime.setObjectName(_fromUtf8("lineFilterTagtime"))
        self.label_13 = QtGui.QLabel(self.groupTerminal_2)
        self.label_13.setGeometry(QtCore.QRect(40, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Basic Tagtime :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineFilterMinlaptime = QtGui.QLineEdit(self.groupTerminal_2)
        self.lineFilterMinlaptime.setGeometry(QtCore.QRect(170, 180, 41, 20))
        self.lineFilterMinlaptime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineFilterMinlaptime.setAutoFillBackground(False)
        self.lineFilterMinlaptime.setStyleSheet(_fromUtf8(""))
        self.lineFilterMinlaptime.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineFilterMinlaptime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineFilterMinlaptime.setReadOnly(True)
        self.lineFilterMinlaptime.setObjectName(_fromUtf8("lineFilterMinlaptime"))
        self.spinMinlaptime = QtGui.QSpinBox(self.groupTerminal_2)
        self.spinMinlaptime.setGeometry(QtCore.QRect(230, 180, 61, 22))
        self.spinMinlaptime.setMaximum(255)
        self.spinMinlaptime.setObjectName(_fromUtf8("spinMinlaptime"))
        self.label_14 = QtGui.QLabel(self.groupTerminal_2)
        self.label_14.setGeometry(QtCore.QRect(40, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Min. Laptime :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupTerminal_2)
        self.label_15.setGeometry(QtCore.QRect(40, 210, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Max. Number of laps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineMaxlapnumber = QtGui.QLineEdit(self.groupTerminal_2)
        self.lineMaxlapnumber.setGeometry(QtCore.QRect(170, 210, 41, 20))
        self.lineMaxlapnumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineMaxlapnumber.setAutoFillBackground(False)
        self.lineMaxlapnumber.setStyleSheet(_fromUtf8(""))
        self.lineMaxlapnumber.setText(QtGui.QApplication.translate("MainWindow", "- -", None, QtGui.QApplication.UnicodeUTF8))
        self.lineMaxlapnumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lineMaxlapnumber.setReadOnly(True)
        self.lineMaxlapnumber.setObjectName(_fromUtf8("lineMaxlapnumber"))
        self.spinMaxlapnumber = QtGui.QSpinBox(self.groupTerminal_2)
        self.spinMaxlapnumber.setGeometry(QtCore.QRect(230, 210, 61, 22))
        self.spinMaxlapnumber.setMaximum(255)
        self.spinMaxlapnumber.setObjectName(_fromUtf8("spinMaxlapnumber"))
        self.label_16 = QtGui.QLabel(self.groupTerminal_2)
        self.label_16.setGeometry(QtCore.QRect(20, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Filters :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushRaceStart = QtGui.QPushButton(self.groupTerminal_2)
        self.pushRaceStart.setGeometry(QtCore.QRect(30, 310, 131, 41))
        self.pushRaceStart.setText(QtGui.QApplication.translate("MainWindow", "START RACE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushRaceStart.setObjectName(_fromUtf8("pushRaceStart"))
        self.pushRaceStop = QtGui.QPushButton(self.groupTerminal_2)
        self.pushRaceStop.setGeometry(QtCore.QRect(170, 310, 91, 41))
        self.pushRaceStop.setText(QtGui.QApplication.translate("MainWindow", "STOP RACE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushRaceStop.setObjectName(_fromUtf8("pushRaceStop"))
        self.labelMeasurementState = QtGui.QLabel(self.groupTerminal_2)
        self.labelMeasurementState.setGeometry(QtCore.QRect(60, 245, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMeasurementState.setFont(font)
        self.labelMeasurementState.setStyleSheet(_fromUtf8("color:#aa0000"))
        self.labelMeasurementState.setText(QtGui.QApplication.translate("MainWindow", "Measurement State", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMeasurementState.setObjectName(_fromUtf8("labelMeasurementState"))
        self.checkRfidRace = QtGui.QCheckBox(self.groupTerminal_2)
        self.checkRfidRace.setGeometry(QtCore.QRect(20, 70, 70, 17))
        self.checkRfidRace.setText(QtGui.QApplication.translate("MainWindow", "RFID Race", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRfidRace.setObjectName(_fromUtf8("checkRfidRace"))
        self.groupTerminal_3 = QtGui.QGroupBox(self.tabTimingSettings)
        self.groupTerminal_3.setEnabled(True)
        self.groupTerminal_3.setGeometry(QtCore.QRect(360, 30, 301, 101))
        self.groupTerminal_3.setAutoFillBackground(False)
        self.groupTerminal_3.setTitle(QtGui.QApplication.translate("MainWindow", "BASIC   M O D E", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTerminal_3.setObjectName(_fromUtf8("groupTerminal_3"))
        self.groupTerminal_4 = QtGui.QGroupBox(self.tabTimingSettings)
        self.groupTerminal_4.setGeometry(QtCore.QRect(360, 140, 301, 111))
        self.groupTerminal_4.setAutoFillBackground(False)
        self.groupTerminal_4.setTitle(QtGui.QApplication.translate("MainWindow", "MANUAL   M O D E", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTerminal_4.setObjectName(_fromUtf8("groupTerminal_4"))
        self.groupTerminal_5 = QtGui.QGroupBox(self.tabTimingSettings)
        self.groupTerminal_5.setGeometry(QtCore.QRect(680, 30, 301, 101))
        self.groupTerminal_5.setAutoFillBackground(False)
        self.groupTerminal_5.setTitle(QtGui.QApplication.translate("MainWindow", "MULTIPLE START MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTerminal_5.setObjectName(_fromUtf8("groupTerminal_5"))
        self.groupTerminal_6 = QtGui.QGroupBox(self.tabTimingSettings)
        self.groupTerminal_6.setGeometry(QtCore.QRect(360, 260, 301, 111))
        self.groupTerminal_6.setAutoFillBackground(False)
        self.groupTerminal_6.setTitle(QtGui.QApplication.translate("MainWindow", "SINGLE  START MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTerminal_6.setObjectName(_fromUtf8("groupTerminal_6"))
        self.tabWidget.addTab(self.tabTimingSettings, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolbar = QtGui.QToolBar(MainWindow)
        self.toolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.toolbarPort = QtGui.QToolBar(MainWindow)
        self.toolbarPort.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarPort.setObjectName(_fromUtf8("toolbarPort"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbarPort)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.aRefresh = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("gui/icons/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aRefresh.setIcon(icon7)
        self.aRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefresh.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefresh.setObjectName(_fromUtf8("aRefresh"))
        self.aSetPort = QtGui.QAction(MainWindow)
        self.aSetPort.setText(QtGui.QApplication.translate("MainWindow", "COM21", None, QtGui.QApplication.UnicodeUTF8))
        self.aSetPort.setObjectName(_fromUtf8("aSetPort"))
        self.aConnectPort = QtGui.QAction(MainWindow)
        self.aConnectPort.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setObjectName(_fromUtf8("aConnectPort"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.aEditMode = QtGui.QAction(MainWindow)
        self.aEditMode.setText(QtGui.QApplication.translate("MainWindow", "EditMode", None, QtGui.QApplication.UnicodeUTF8))
        self.aEditMode.setObjectName(_fromUtf8("aEditMode"))
        self.aRefreshMode = QtGui.QAction(MainWindow)
        self.aRefreshMode.setText(QtGui.QApplication.translate("MainWindow", "RefreshMode", None, QtGui.QApplication.UnicodeUTF8))
        self.aRefreshMode.setObjectName(_fromUtf8("aRefreshMode"))
        self.aLockMode = QtGui.QAction(MainWindow)
        self.aLockMode.setText(QtGui.QApplication.translate("MainWindow", "LockMode", None, QtGui.QApplication.UnicodeUTF8))
        self.aLockMode.setObjectName(_fromUtf8("aLockMode"))
        self.aDirectWwwExport = QtGui.QAction(MainWindow)
        self.aDirectWwwExport.setText(QtGui.QApplication.translate("MainWindow", "Direct WWW Export", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectWwwExport.setShortcut(QtGui.QApplication.translate("MainWindow", "F12", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectWwwExport.setObjectName(_fromUtf8("aDirectWwwExport"))
        self.aShortcuts = QtGui.QAction(MainWindow)
        self.aShortcuts.setText(QtGui.QApplication.translate("MainWindow", "Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.aShortcuts.setObjectName(_fromUtf8("aShortcuts"))
        self.aDirectExportCategories = QtGui.QAction(MainWindow)
        self.aDirectExportCategories.setText(QtGui.QApplication.translate("MainWindow", "Direct Export Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectExportCategories.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.aDirectExportCategories.setObjectName(_fromUtf8("aDirectExportCategories"))
        self.menuDatabase.addAction(self.actionLoad)
        self.menuDatabase.addAction(self.actionSave)
        self.menuDatabase.addAction(self.actionSave_as)
        self.menuActions.addAction(self.aRefresh)
        self.menuActions.addAction(self.aSetPort)
        self.menuActions.addAction(self.aConnectPort)
        self.menuActions.addAction(self.actionAbout)
        self.menuActions.addAction(self.actionHelp)
        self.menuActions.addAction(self.aEditMode)
        self.menuActions.addAction(self.aRefreshMode)
        self.menuActions.addAction(self.aLockMode)
        self.menuActions.addAction(self.aDirectExportCategories)
        self.menuActions.addAction(self.aDirectWwwExport)
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolbar.addAction(self.aRefresh)
        self.toolbarPort.addAction(self.aSetPort)
        self.toolbarPort.addAction(self.aConnectPort)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRuns_Times), QtGui.QApplication.translate("MainWindow", "Runs#Times", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUsers), QtGui.QApplication.translate("MainWindow", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCategories), QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCGroups), QtGui.QApplication.translate("MainWindow", "Category Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTags), QtGui.QApplication.translate("MainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTerminal), QtGui.QApplication.translate("MainWindow", "Terminal#Cells", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTimingSettings), QtGui.QApplication.translate("MainWindow", "Timing Settings", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

